console.log(`PID del proceso: ${process.pid}`)
console.log(`Nombre del proceso: ${process.title}`)
console.log(`UID del proceso: ${process.getuid ? process.getuid() : 'No disponible en este sistema'}`)
//console.log(`Argumentos del proceso: ${process.argv}`)
console.log(`Plataforma usada: ${process.platform}`)
const memoryUsage = process.memoryUsage()
console.log('Uso de memoria del proceso:')
console.log(`RSS: ${memoryUsage.rss} bytes`)
console.log(`Heap Total: ${memoryUsage.heapTotal} bytes`)
console.log(`Heap Used: ${memoryUsage.heapUsed} bytes`)
console.log(`External: ${memoryUsage.external} bytes`)
//console.log(`Variables de entorno del proceso ${JSON.stringify(process.env)}`)
const cpuUsage = process.cpuUsage()
console.log(cpuUsage)
console.log(`Tiempo desde que inicio: ${process.uptime()}`)
process.exit()

